let x=10;
x=20;
let y="Hello";
let z: number;
z=20;
let a: number =10;
let b: string ="Hello";
let c:boolean =true;
let d: any= 10;
let e:number[]=[1,2,3];
let f: string[] = ["Hello","World"];
let g: boolean[]=[true,false];
let h: any[]=[1,"Hello",true];
let i:[string,number]=["Hello",10];
let j:object={name: "John",age: 30,emailId: {email:"asc@s.com"}, preferences:["sports","music"]};
let k: any = "Hello"; // any
let l: any = true;

console.log(`a: ${typeof a}`);
console.log(`b: ${typeof b}`);
console.log(`c: ${typeof c}`);
console.log(`d: ${typeof d}`);
console.log(`e: ${typeof e}`);
console.log(`f: ${typeof f}`);
console.log(`g: ${typeof g}`);
console.log(`h: ${typeof h}`);
console.log(`i: ${typeof i}`);
console.log(`j: ${typeof j}`);
console.log(`k: ${typeof k}`);
console.log(`l: ${typeof l}`);

console.log(`a: ${a}`);
console.log(`b: ${b}`);
console.log(`c: ${c}`);
console.log(`d: ${d}`);
console.log(`e: ${e}`);
console.log(`f: ${f}`);
console.log(`g: ${g}`);
console.log(`h: ${h}`);
console.log(`i: ${i}`);
console.log(`j: ${j}`);
console.log(`k: ${k}`);
console.log(`l: ${l}`);